name: CI/CD Workflow for Project1 Spring Boot Deployment

on:
  push:
    paths:
      - 'vehicle/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test Project1 with Gradle
        working-directory: ./vehicle
        run: ./gradlew clean build -x test

      - name: Build Docker Image for vehicle
        working-directory: ./vehicle
        run: docker build -t <DOCKERHUB_USERNAME>/vehicle-springboot-app:${{ github.sha }} .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push <DOCKERHUB_USERNAME>/project1-springboot-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Set up Kubernetes context
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy vehicle to Kubernetes
        run: |
          kubectl set image deployment/vehicle-springboot-app vehicle-springboot-app=<DOCKERHUB_USERNAME>/vehicle-springboot-app:${{ github.sha }}
          kubectl rollout status deployment/vehicle-springboot-app
